// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDefaultSaveDir():Promise<string>;

export function GetHomeDir():Promise<string>;

export function GetSystemClipboard():Promise<string>;

export function ReadDir(arg1:string):Promise<Array<main.FileEntry>>;

export function SelectDirectory():Promise<string>;

export function SetSystemClipboard(arg1:string):Promise<void>;

export function StartClipboardServer(arg1:string):Promise<main.ServerResponse>;

export function StartReceiveServer(arg1:string,arg2:string):Promise<main.ServerResponse>;

export function StartServer(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:number):Promise<main.ServerResponse>;

export function StopServer():Promise<void>;
