// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function StartServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartServer'](arg1, arg2, arg3);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
