// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultSaveDir() {
  return window['go']['main']['App']['GetDefaultSaveDir']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetSystemClipboard() {
  return window['go']['main']['App']['GetSystemClipboard']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetSystemClipboard(arg1) {
  return window['go']['main']['App']['SetSystemClipboard'](arg1);
}

export function StartClipboardServer(arg1) {
  return window['go']['main']['App']['StartClipboardServer'](arg1);
}

export function StartReceiveServer(arg1, arg2) {
  return window['go']['main']['App']['StartReceiveServer'](arg1, arg2);
}

export function StartServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartServer'](arg1, arg2, arg3, arg4, arg5);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
